-- Drop tables
DROP TABLE files;
DROP TABLE word_counts;

-- Create a table to store results
CREATE TABLE files (lines STRING);

-- Load data into the database using a file on your local system (NOT HDFS)
LOAD DATA LOCAL INPATH '/root/input.txt' INTO TABLE files;

-- Perform MapReduce
CREATE TABLE word_counts AS
SELECT word, count(1) AS count FROM
(SELECT explode(split(lines, ' ')) AS word FROM files) w
GROUP BY word
ORDER BY word;

-- View word counts
SELECT * FROM word_counts;
